# Generated by Django 3.2.9 on 2021-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oim_connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFightCondition',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('FightID', models.BigIntegerField(default=0)),
                ('Turn', models.IntegerField(default=0)),
                ('UnitsPositions', models.TextField(default='')),
            ],
        ),
    ]
